### ISSUE TITLE
您好，问您一个关于hao123的问题。

### ISSUE THREAD

**Issue by legendRD** [hao123-fe/her#22]
为什么没有使用session和cookie，hao123还是能保存我定制频道的信息？
![qq 20150817113437](https://cloud.githubusercontent.com/assets/12531965/9297586/6d471dd8-44d4-11e5-87e5-dccc4cea26c2.jpg)

**Comment by allen-zh** [comment]
跟本项目无关

**Comment by legendRD** [comment]
是你不会php吧？
